name: .NET Core

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build
      run: devenv /build release ./WallyApp.sln
