name: Build UWP Apps


on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build
      run: |
        dir
        echo "This is a custom message"
        msbuild WallyApp.sln /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Always 
