name: Build UWP Apps


on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    - name: Build
      run: MSBuild.exe WallyApp.sln /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Always
