name: .NET Core

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build
      run: MSBuild.exe .\WallyApp.sln /p:Configuration=Release /p:Platform=x64 /p:AppxBundle=Always
